# Spring properties
spring:
  application:
     name: auth-service  # Service registers under this name

server.port: 9205   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka