spring:
  application:
     name: auth-service

server:
  port: 9205

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka

shop:
  jwt:
    privateKey: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCdLtr1v2frotQ6
      5bWDKSYVo0woZeKoQSZJk3bgBs/k6G/CLY/ibLaQB3Zdn4qI1k9ZGT9DDuPFAtf/
      RM3lVQZ0OwSrYm4d3JA17MZul3Myc6DuOHhtE4009x3Tbdza/wJHE0pDY/q5tEOc
      NGEgYHzTxk2Ys0Nducsr3sU6NJ+OYttfVcV5slyLwtSb78nWlwT9KXsZ/LINKf8n
      kIH08ytPlkHDq8e8ao7SkkSghUpOWeNkmDrUHjFVjIzwbauAhM0XW2ga+gDuqrhN
      gwIR3/zUb0zmAImAcro99U8/dOjbrKJvskBkDW+eURrL8CcVFC3kFdw8EL1cwqq7
      hK3XU4uJAgMBAAECggEAAb+Yre0gIc3g4HrXpwrZIpp7aWOgvtBitaTPSLSqsVgo
      jhdlp1YgPb/ngCkbKGSB43LVclCDFhjvACbqx2dHuBlD9wgUQ37Fl+P3XRmQLXp9
      ysiUBlqWUoWBLm3lbAY0J0g+pjtBeblYmy81+V85ZD2rdUxhLnS3nthOh1Q4hiPs
      6E/VR5T6FlgJQwrTNPugF+MLxe6ENkq5RCCa4H4JDAAJhOBGdt1fJYtXDgZRBgqn
      /PkcZ33jWJ0o05AVebGU8ccVL+B5IrDUYWv0UPhNgNpdtX4t4c/RklAjWWLI1KLn
      cJ3SXBM9XLp3kftnXI/+z++C4aC+PiNPC9B3MdmwdQKBgQDI7pnpkSUPSQt61Bla
      Nupp6EtyJaRCFGhi1HYdditcYB9p5ZqGi307/a4ZkqF4T5/lioHm+93CJ4AheXZF
      PAsrJmvTo+iR9t3FEPBTP80e/q/rZ76+Xi8+aIenD6brtgoweXRpFZrvDYSJIn74
      odF7qlB0nxT3V3u/pZrdufCjbwKBgQDIQtJ6I3UwAE1v4GOEaPODuYPnmf59CDrr
      CcEx5KZCGvqzBoYSyb3pguYQlrbapf51YOZvufLiL6B1CzCgSbj4M6XY9Oej77xr
      mSnGufoeZRG1Hsd0wArPt1R93OHt5iqruLIV2aZSORFK63hvbYQ7jknbzN+5xYW2
      XhLlbMpkhwKBgCRwSM83uD3OZFuRDUvz+4zbSJtZwjENnGSX3Re4r2JgODIvJlfS
      AhMYDTOsCMZVwkyRUr9925hzK2Rmr5Ecs3XO0O0fo3SdDVjImpyuTFebnnGVbdz+
      HZk2wasFRqMmbzCdRgQsm91QWUG5VMdoKSJBH7gWhWnZnqKBuNUO/FnXAoGBALFL
      X5YccDJ4AharHM/sLrMO+fWAQ2skby0I7M6kNIFP62W1v9tAWm8yoUZMeERpMzdt
      +3UsthiDu9YDeyBdRHIRH6JNaAqeQz0rU24J1qM0LZIhVspI/wlYsGfhtu/slxiC
      or9veq1Osr2WbICR/8DOPxtmbSfF9JQ5Axe00hZfAoGATCJW6YOFjrSGGV8OCzuB
      GFwX8W3fmhu5rh9IXcWDAAaqgi68C6wwuKIn2wf/S0lZ0UYMbrYWrLTIiTzKH3B1
      CApDGKHpcPVErC2Uee1dayAFrJmIjrZO8jVYM2q2aUCZot8fKAs44hY+430Eg0Xw
      qHh+3EUA1pC3MQmKuHEyfG0=
      -----END PRIVATE KEY-----