# Spring Properties
spring:
  application:
     name: web-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka

# HTTP Server
server:
  port: 9222   # HTTP (Tomcat) port