spring:
  application:
     name: gateway-service
  main:
    allow-bean-definition-overriding: true

server:
  port: 9206

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka

zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  prefix: /api
  routes:
    user-service:
      path: /user/**
      service-id: USER-SERVICE
    auth-service:
      path: /auth/**
      service-id: AUTH-SERVICE
    cart-service:
      path: /cart/**
      service-id: CART-SERVICE
    product-service:
      path: /product/**
      service-id: PRODUCT-SERVICE
    keyword-service:
      path: /keyword/**
      service-id: PRODUCT-SERVICE
    category-service:
      path: /category/**
      service-id: PRODUCT-SERVICE