# Spring properties
spring:
  application:
     name: gateway-service  # Service registers under this name
  main:
    allow-bean-definition-overriding: true

server.port: 9206   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    user-service:
      path: /users/**
      service-id: USER-SERVICE
    auth-service:
      path: /auth/**
      service-id: AUTH-SERVICE
    cart-service:
      path: /carts/**
      service-id: CART-SERVICE
    product-service:
      path: /products/**
      service-id: PRODUCT-SERVICE
    keyword-service:
      path: /keywords/**
      service-id: PRODUCT-SERVICE
    category-service:
      path: /categories/**
      service-id: PRODUCT-SERVICE