# Spring properties
spring:
  application:
     name: gateway-service  # Service registers under this name
  main:
    allow-bean-definition-overriding: true

server.port: 9206   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka

zuul:
  routes:
    user-service:
      path: /users/**
      service-id: USER-SERVICE
      stripPrefix: false
      sensitive-headers: Cookie,Set-Cookie
    auth-service:
      path: /auth/**
      service-id: AUTH-SERVICE
      stripPrefix: false
      sensitive-headers: Cookie,Set-Cookie
    cart-service:
      path: /cart/**
      service-id: CART-SERVICE
      stripPrefix: false
      sensitive-headers: Cookie,Set-Cookie
    product-service:
      path: /products/**
      service-id: PRODUCT-SERVICE
      stripPrefix: false
      sensitive-headers: Cookie,Set-Cookie
    web-service:
      path: /**
      service-id: WEB-SERVICE
      stripPrefix: false
      sensitive-headers: Cookie,Set-Cookie