spring:
  application:
     name: gateway-service

server:
  port: 9206

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka

zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  prefix: /api
  routes:
    user-service:
      path: /user-service/**
      service-id: USER-SERVICE
    auth-service:
      path: /auth-service/**
      service-id: AUTH-SERVICE
    cart-service:
      path: /cart-service/**
      service-id: CART-SERVICE
    product-service:
      path: /product-service/**
      service-id: PRODUCT-SERVICE
    keyword-service:
      path: /keyword-service/**
      service-id: PRODUCT-SERVICE
    category-service:
      path: /category-service/**
      service-id: PRODUCT-SERVICE