# Spring properties
spring:
  application:
     name: product-service  # Service registers under this name
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:shop_online}
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PSW:pass}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

server.port: 9202   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka


logging.level.org.springframework.security: DEBUG