spring:
  application:
     name: product-service
  main:
    allow-bean-definition-overriding: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

server:
  port: 9202

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka