spring:
  application:
     name: product-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:shop_online}
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PSW:pass}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

server:
  port: 9202

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka