docs:
  swagger:
    api:
      info:
        title: Online shop application
        description: It's a simple example of using Spring Cloud.
        version: 1.0.0
        termsOfServiceUrl: https://github.com/zonclayv/online-shop
        contactName: Aleh Haidash
        contactUrl: https://github.com/zonclayv/
        contactEmail: aleh.haidash@gmail.com
        licenseName: GNU General Public License v3.0
        licenseUrl: https://github.com/zonclayv/online-shop/blob/master/LICENSE
docs.title: Online shop application
description: It's a simple example of using Spring Cloud.
version: 1.0.0
termsOfServiceUrl: https://github.com/zonclayv/online-shop
contactName: Aleh Haidash
contactUrl: https://github.com/zonclayv/
contactEmail: aleh.haidash@gmail.com
licenseName: GNU General Public License v3.0
licenseUrl: https://github.com/zonclayv/online-shop/blob/master/LICENSE