spring:
  application:
     name: cart-service
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

server:
  port: 9204

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka

