spring:
  application:
    name: registration-server

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5 # DO NOT DO THIS IN PRODUCTION
  client:  # Not a client, don't register with yourself (unless running
           # multiple discovery servers for redundancy)
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:9200/eureka

server:
  port: 9200