# Spring properties
spring:
  application:
     name: cart-service  # Service registers under this name

server.port: 9204   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka
